site_name: Understanding ZK Regex
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
locale: en
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
nav:
  - Introduction: index.md
  - Preconcepts: preconcepts.md
  - Structures: structures.md
  - Obtaining DFA: obtain_dfa.md
  - Obtaining circuit: obtain_circom.md
